# Numpy

Numpy es un paquete de computación científica. Permite el trabajo con arreglos vectoriales, matriciales y funciones para cálculos matemáticos, también permite operaciones de algebra lineal, transformadas de Fourier y generación de valores aleatorios. Para mayor información ir a: __[Numpy](https://docs.scipy.org/doc/numpy/user/quickstart.html)__

En este notebook se abordarán temas como:

### [1. Crear arreglos (arrays) utilizando NumPy](#Cap1)

### [2. Información de los arreglos](#Cap2)

### [3. Acceder y modificar elementos en un arreglo](#Cap3)

### [4. Acceder a sub arreglos](#Cap4)

### [5. Partición de datos](#Cap5)

### [6. Operaciones con arreglos](#Cap6)

### [7. Operaciones booleanas](#Cap7)

### [8. Ordenar arreglos](#Cap8)

### [9. Centrar un arreglo](#Cap9)

In [ ]:
import numpy as np

###  1. Crear arreglos (arrays) utilizando NumPy<a class="anchor" id='Cap1'></a>

In [ ]:
np?

Los arrays son arreglos de datos en diferentes dimensiones, similares a las listas pero más eficientes, por lo que la manipulación de datos en python es sinónimo de manipulación en Numpy, incluso en el uso de otras herramientas como Pandas

Estos arreglos deben tener el mismo tipo de dato para realizar las operaciones entre ellos y para su creación

In [ ]:
# Crear un vector o array de 1 dimensión

a = np.array([12,32,34,32,22,15])

# Crear una matriz o array de 2 dimensiones

b = np.array([[12,13,54],[12,32,1],[21,3,4]])
print( a,"\n\n", b)

In [ ]:
# Qué sucede si se crea un array con diferentes tipos de variables

c = np.array(["1",2,3,4.5])
print(c) # Numpy modifica el tipo de la variable para que todas sean iguales (respecto al tipo)

Para crear algunos arreglos específicos NumPy cuenta con funciones pre definidas

In [ ]:
# Crear un array de 0
print(np.zeros(10,dtype="int"))

In [ ]:
# Crear una matriz de 1

print(np.ones((3,4),dtype="float"))

In [ ]:
# Crear una matriz con un valor cualquiera (i.e 14.8)

print(np.full((2,3),14.8,dtype="float"))

In [ ]:
# Crear una matriz identidad

print(np.eye(4))

In [ ]:
# Crear un arreglo entre dos valores (0,20) tomando cierto tamaño de "paso" (2)

print(np.arange(0,20,2))

In [ ]:
# Crear una matriz de valores aleatorios

print(np.random.rand(5,5)) # Número de filas y número de columnas

### 2. Información de los arreglos<a class="anchor" id='Cap2'></a>

In [ ]:
np.random.seed(0) # Asignar y mantener fija la semilla en el generador de valores aleatorios

x = np.random.randint(10,size=(3,4))
print(x)

Para conocer las características de los arreglos como dimensiones, forma y tamaño se utilizan los siguientes métodos:

In [ ]:
# Dimensiones (ndim)

print(x.ndim)

In [ ]:
# Forma

print(x.shape)

In [ ]:
# Tamaño

print(x.size)

### 3. Acceder y modificar elementos en los arreglos<a class="anchor" id='Cap3'></a>

El acceso y modificación de un elemento en un array se hace de manera similar a las listas, es decir, usando [fila,columna]

In [ ]:
# Acceder al primer elemento

print("Primer elemento: ",x[0])

In [ ]:
# Acceder al último elemento

print("Último elemeno: ",x[-1])

In [ ]:
# Acceder a cualquier elemento (i.e tercer elemento de la primera fila)

print(x[0,3])

In [ ]:
# Modificar un elemento 

x[1]=3.16 # Modificar todos los elementos de la fila 1
print(x)

### 4. Acceder a sub-arreglos<a class="anchor" id='Cap4'></a>

Al igual que en las listas, para acceder a porciones o sub-arreglos se usa la notación:

x[comienzo:final:paso]

In [ ]:
# Arreglo unidimensional

x1=[12,7,34,5,6,78]
print(x1)
print(x1[:2])

In [ ]:
# Dos últimos elementos

print(x1[-2:])

In [ ]:
# Elementos cada dos observaciones

print(x1[::2] )

In [ ]:
# Arreglo multidimensional

print(x)

In [ ]:
# Primera columna

print(x[:,0])

In [ ]:
# Primeras dos filas y tres columnas

print(x[:2,:3])

In [ ]:
# Todas las filas y columnas intercaladas
print(x[:,::2])

### 5. Particionar los datos<a class="anchor" id='Cap5'></a>

En algunos casos es preciso modificar la forma de un array, por lo que la función reshape resulta util para esta tarea

In [ ]:
grid = np.arange(16) # Se crea un array unidimensional con 16 elementos
grid = grid.reshape((4,4)) # Se modifica a una matriz de 4x4
print(grid)

In [ ]:
# Partición vertical en dos de un arreglo (de forma equitativa)
upper, lower = np.vsplit(grid,2) 
print(upper)
print(lower)

In [ ]:
# Partición horizontal en dos de un arreglo (de forma equitativa)

left,right = np.hsplit(grid,[2])
print("\n",left)
print(right)

### 6. Operaciones con los arreglos<a class="anchor" id='Cap6'></a>

* Funciones aritméticas

En la siguiente tabla se enlistan los operadores aritméticos implementados en NumPy:

| Operador	    | Equivalente ufunc | Descripción                           |
|---------------|-------------------|---------------------------------------|
|``+``          |``np.add``         |Suma (e.g., ``1 + 1 = 2``)             |
|``-``          |``np.subtract``    |Resta (e.g., ``3 - 2 = 1``)            |
|``-``          |``np.negative``    |Negativo unitario (e.g., ``-2``)       |
|``*``          |``np.multiply``    |Multiplicación (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``      |División (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``|División inferior (e.g., ``3 // 2 = 1``)|
|``**``         |``np.power``       |Potenciación (e.g., ``2 ** 3 = 8``)    |
|``%``          |``np.mod``         |Módulo/residuo (e.g., ``9 % 4 = 1``)   |


In [ ]:
%timeit sum(x1)

In [ ]:
%timeit np.array(x).sum()

In [ ]:
print(grid,"\n")
print(np.floor_divide(grid,3)) # Aproximación al entero inferior

* Funciones trigonométricas

In [ ]:
theta=np.linspace(0,np.pi,3)
print(theta)
print("\n Seno(theta):",np.sin(theta))
print("\n Coseno(theta):",np.cos(theta))
print("\n Tangente(theta):",np.tan(theta))

* Funciones logarítmicas y exponenciales

In [ ]:
# Funciones exponenciales
x = [1, 2, 3]
print("x:   ", x)
print("x^3: ", np.power(x,3))
print("e^x: ", np.exp(x))
print("2^x: ", np.exp2(x))
print("3^x: ", np.power(3, x))

In [ ]:
# Funciones logarítmicas
x = [1, 2, 4, 10]
print("x        :", x)
print("ln(x)    :", np.log(x))
print("log2(x)  :", np.log2(x))
print("log10(x) :", np.log10(x))

* Otras funciones

In [ ]:
print(x,"\n")
print(np.multiply.reduce(x))     # Reducir el arreglo a una sola operación. Regresa el producto de todos los elementos
print(np.multiply.accumulate(x)) # Multiplica todos los elementos y almacena los productos intermedios

Para la multiplicación de matrices se usa la función np.dot(), en el caso de querer multiplicar elemento por elemento se acude a " * "

In [ ]:
# Para el producto de las matrices se debe cumplir que las dimensiones sean: (mxn)*(nxp)=mxp

a=np.random.rand(4,5) # Matriz de 4x5
b=np.random.randint(0,5,size=[5,3]) # Matríz de 5x3
n=a.dot(b)
print(n)

In [ ]:
# La función transpose regresa la transupuesta de una matriz

trans=a.transpose()
print("Transpuesta de la matriz: \n\n",trans)

In [ ]:
# Inversa de una matriz. Es preciso acudir al modulo de álgebra lineal (linalg)

matriz=np.random.randint(4,100,[4,4])
inv=np.linalg.inv(matriz)
print(matriz,"\n")
print(inv,"\n") # Matriz inversa
print(matriz.dot(inv)) # Matriz identidad

In [ ]:
# Determinante de una matriz

np.linalg.det(matriz)

In [ ]:
# La función flatten transforma un arreglo n-dimensional en uno uni dimensional

uni=a.flatten()
print(uni,"\n",uni.shape)

### 7. Operaciones booleanas<a class="anchor" id='Cap7'></a>

In [ ]:
x=np.random.randint(low=0,high=10,size=(4,2))
x

In [ ]:
# Para comparar elementos de un arreglo se hace uso de los operadores booleanos

print(x>4) # Como salida se obtiene el arreglo del mismo tamaño, pero con valores de true cuando se cumple la condición

In [ ]:
# Los valores de True son iguales a 1, para contar cuantos valores cumplen con una condición se hace uso de count_nonzero()

print(np.count_nonzero(x>5),"valores son mayores a 5")
print(np.count_nonzero(~(x>=5)),"valores no son mayores a 5")
print(np.count_nonzero((x>5)&(x<8)),"valores son mayores a 5 y menores a 8")
print(np.count_nonzero((x>5)|(x<8)),"valores son mayores a 5 o menores a 8")

In [ ]:
# Para seleccionar un subconjuto de datos que cumpla una condición se crea una "máscara"

mask=x>6
print("Los valores mayores 6 son:",x[mask])

Los operadores and y or no son equivalentes a & y |, dado que los primeros toman una única entidad para realizar las comparaciones, mientras que los segundos lo hacen elemento por elemento

### 8. Ordenar los arreglos<a class="anchor" id='Cap8'></a>

Para ordenar los arreglos en NumPy se pueden usar bucles, sin embargo resulta más eficiente utilizar las funciones con las que se cuenta como sort() o argsort

In [ ]:
x = np.random.randint(0,20,10)
x

In [ ]:
# Ordenar los valores de menor a mayor
print(np.sort(x))

# Ordenar de menor a mayor, pero regresando los índicies de los valores ordenados
print(np.argsort(x))

In [ ]:
z=np.random.randint(0,10,(4,6))
z

In [ ]:
# Ordenar las columnas
print(np.sort(z,axis=0))

# Ordenar las filas
print("\n",np.sort(z,axis=1))

### 9. Centrar un arreglo<a class="anchor" id='Cap9'></a>

En algunas situaciones es de bastante utilidad centrar los datos para garantizar una media igual a 0 y una varianza igual a uno. Numpy ofrece la posibilidad de hacerlo de manera eficiente con el manejo de arrays

In [15]:
X = np.random.random((10, 3))
X

array([[0.20678259, 0.27332964, 0.11153613],
       [0.56686676, 0.64154383, 0.33465253],
       [0.41476713, 0.59449233, 0.34954072],
       [0.54286397, 0.53022824, 0.98529447],
       [0.43279027, 0.54135912, 0.19967596],
       [0.43443949, 0.79843022, 0.20875892],
       [0.59423718, 0.01956257, 0.81897948],
       [0.57291025, 0.81315426, 0.26534086],
       [0.22495809, 0.71762752, 0.10569849],
       [0.63906551, 0.31020036, 0.08536184]])

In [16]:
# Cálculo de la media 

Xmean = X.mean(1)
Xmean

array([0.19721612, 0.51435437, 0.45293339, 0.68612889, 0.39127512,
       0.48054288, 0.47759308, 0.55046846, 0.34942803, 0.3448759 ])

In [18]:
import pandas as pd

M = pd.DataFrame(X)
M

0         1         2
0  0.206783  0.273330  0.111536
1  0.566867  0.641544  0.334653
2  0.414767  0.594492  0.349541
3  0.542864  0.530228  0.985294
4  0.432790  0.541359  0.199676
5  0.434439  0.798430  0.208759
6  0.594237  0.019563  0.818979
7  0.572910  0.813154  0.265341
8  0.224958  0.717628  0.105698
9  0.639066  0.310200  0.085362

### Ejercicio


1) Cree un arreglo unidimensional con los siguientes valores:

    46, 5, 19, 47, 22, 45, 11, 11, 33, 7, 26, 48, 7, 47, 32, 36, 18, 23, 21, 2
    
    - ¿Cuál es su tamaño, dimensión y forma?

2) Convierta el arreglo anterior en una matriz de 6x3, ¿Es posible?, de no ser así proponga una forma que sí lo permita.

3) ¿Cuál es el valor de la posición (2,3)? Cambie su valor por 8

4) De la matriz extraiga la primera y última fila y cree dos variables nuevas. ¿Cuál es el valor de su suma?

5) Cree una matriz de enteros de tamaño 20 y ordene sus valores 

6) Considere el siguiente arreglo de estaturas para un grupo de person:

    - [189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 168, 170, 178, 182, 180,
       183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188,
       188, 182, 185]
       
    - Calcule el promedio, desviación estándar, máximo y mínimo

In [1]:
import numpy as np

In [4]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [9]:
M = np.ones((3, 2))
a = np.arange(3)
M

array([[1., 1.],
       [1., 1.],
       [1., 1.]])